### ISSUE TITLE
remove import vtk

### ISSUE THREAD

**Issue by paskino** [vais-ral/CILViewer#348] opened 2023-06-16 21:08 UTC
According to [VTK documentation](https://vtk.org/doc/nightly/html/md__builds_gitlab_kitware_sciviz_ci_Documentation_Doxygen_PythonWrappers.html) 

> the advantage (and disadvantage) of [ the use of `import vtk` ] is that it imports everything. It requires just one import statement for all of VTK, but it can be slow because VTK has grown to be very large over the years.

Therefore we should avoid `import vtk` and import the `vtkmodule` that is required.

**Comment by lauramurgatroyd** [comment] 2023-07-03 08:58
closing as this is a duplicate of https://github.com/vais-ral/CILViewer/issues/286

**Closed by lauramurgatroyd** 2023-07-03 08:58 UTC
