### ISSUE TITLE
complete CI builds as CIL

### ISSUE THREAD

**Issue by paskino** [vais-ral/CILViewer#105] opened 2021-04-20 09:00 UTC
this repo should have the same CI [variants ](https://github.com/vais-ral/CCPi-Framework/tree/master/recipe)as CIL.

**Comment by lauramurgatroyd** [comment] 2021-04-23 13:17
Re-opening this because despite the fact that [the pull request succesfully built](https://anvil.softeng-support.ac.uk/jenkins/job/CILsingle/job/CCPi-Viewer-dev/lastBuild/console), [master did not build](https://anvil.softeng-support.ac.uk/jenkins/job/CILsingle/job/CCPi-Viewer/44/console) when it was merged.

I think the problem is that in CCPi-Viewer dev :
`CCPI_BUILD_ARGS='-c conda-forge -c ccpi -c paskino'`

but in CCPi-Viewer:
`CCPI_BUILD_ARGS='-c paskino'`

and as a result it can't find vtk.

Where do we set` CCPI_BUILD_ARGS`?

**Comment by lauramurgatroyd** [comment] 2021-04-26 11:57
Fixed by modifying the jenkins build configuration so that CCPI_BUILD_ARGS='-c conda-forge -c ccpi -c paskino'

**Closed by lauramurgatroyd** 2021-04-26 11:57 UTC
Labels: question
